name: persona_app
services:
  maria_db:
    container_name: maria_db
    image: mariadb:11.4
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s 
    volumes:
        - maria_db_data:/var/lib/mysql
        - ./scripts/maria:/docker-entrypoint-initdb.d

  mongo_db:
    container_name: mongo_db
    image: mongodb/mongodb-community-server:8.0.3-ubuntu2204
    environment:
       MONGODB_INITDB_ROOT_USERNAME: persona_db
       MONGODB_INITDB_ROOT_PASSWORD: persona_db
       MONGODB_INITDB_DATABASE: persona_db
    ports:
      - "27017:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mongo_db_data:/data/db
      - ./scripts/mongo:/docker-entrypoint-initdb.d

  rest_api:
    container_name: rest_api
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        MARIADB_HOST: maria_db
        MARIADB_USER: root
        MARIADB_PASSWORD: password
        MARIADB_DATABASE: persona_db
        MONGODB_HOST: mongo_db
        MONGODB_USER: persona_db
        MONGODB_PASSWORD: persona_db
        MONGODB_DATABASE: persona_db
    ports:
      - "3000:3000"
    depends_on:
      maria_db:
        condition: service_healthy
      mongo_db:
        condition: service_healthy

volumes:
    maria_db_data:
    mongo_db_data:

networks:
    default:
        driver: bridge